version: "3.8"

services:
  management:
    image: mysql/mysql-cluster
    container_name: management1
    command: ndb_mgmd
    networks:
      cluster_net:
        ipv4_address: 192.168.0.2

  ndb1:
    image: mysql/mysql-cluster
    container_name: ndb1
    command: ndbd
    depends_on:
      - management
    networks:
      cluster_net:
        ipv4_address: 192.168.0.3

  ndb2:
    image: mysql/mysql-cluster
    container_name: ndb2
    command: ndbd
    depends_on:
      - management
    networks:
      cluster_net:
        ipv4_address: 192.168.0.4

  mysql1:
    image: mysql/mysql-cluster
    container_name: mysql1
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
    depends_on:
      - ndb1
      - ndb2
    ports:
      - "3307:3306"
    volumes:
      - mysql1_data:/var/lib/mysql
    networks:
      cluster_net:
        ipv4_address: 192.168.0.10

volumes:
  mysql1_data:

networks:
  cluster_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
